### ISSUE TITLE
introduce pcre2el into ruby-test-mode to make regexp more simple and clear.

### ISSUE THREAD

**Issue by zw963** [r0man/ruby-test-mode#28]
Here are some example about my refactored `ruby-test-implementation-filename-mapping`.

```cl
(require 'pcre2el)

(defcustom ruby-test-implementation-filename-mapping
  '(
    ((pcre-to-elisp "(.*)/spec/routing/routes_spec\\.rb$") "\\1/config/routes.rb")
    ((pcre-to-elisp "(.*)/test/routing/routes_test\\.rb$") "\\1/config/routes.rb")

    ((pcre-to-elisp "(.*)/spec/(controllers|models|views|helpers|mailers|uploaders|api)/(.*)_spec\\.rb$") "\\1/app/\\2/\\3.rb")
    ((pcre-to-elisp "(.*)/test/(controllers|models|views|helpers|mailers|uploaders|api)/(.*)(_test)\\.rb$") "\\1/app/\\2/\\3.rb")

    ((pcre-to-elisp "(.*)/spec/(.*)_spec\\.rb$") "\\1/lib/\\2.rb")
    ((pcre-to-elisp "(.*)/test/(.*)_test\\.rb$") "\\1/lib/\\2.rb")

    ((pcre-to-elisp "(.*)/spec/(.*)_tasks_spec\\.rb$") "\\1/\\2.rake")
    ((pcre-to-elisp "(.*)/test/(.*)_tasks_test\\.rb$") "\\1/\\2.rake")

    ((pcre-to-elisp "(.*)/test/unit/(.*)_test\\.rb$") "\\1/app/models/\\2.rb" "\\1/lib/\\2.rb")
    ((pcre-to-elisp "(.*)/test/functional/(.*)_test\\.rb$") "\\1/app/controllers/\\2.rb")

    ((pcre-to-elisp "(.*)(_spec|_test)\\.rb$") "\\1.rb")
    )
  "Regular expressions to map Ruby implementation to unit
filenames). The first element in each list is the match, the
second the replace expression."
  :type '(list)
  :group 'ruby-test)
```

To write regexp like this, we just need `(require 'pcre2el)` to import this library.
please see [here](https://github.com/joddie/pcre2el) for more details. 

This use ruby regexp to write regexp, it more familiar, and less fault, And
somelike more efficient.

e.g. 
`(pcre-to-elisp "(.*)(_spec|_test)\.rb")` 
change to:`
 "\\(.*\\)\\(\\(?:_\\(?:spec\\|test\\)\\)\\).rb"`

`(pcre-to-elisp "(.*)/spec/(controllers|models|views|helpers|mailers|uploaders|api)/(.*)_spec\.rb$")`
change to:
``"\\(.*\\)/spec/\\(\\(?:api\\|\\(?:controller\\|helper\\|m\\(?:ailer\\|odel\\)\\|uploader\\|view\\)s\\)\\)/\\(.*\\)_spec.rb$"``

**Comment by zw963** [comment]
I hope we could discuss about this, and finally, could make `ruby-test-mode` more mapping rule standard,
and write rule more simple.

Thanks.

**Comment by zw963** [comment]
For current version pcre2el, we must match all digtal with ``(rxt-pcre-to-elisp "(\\d+)")``, not standard regexp ``(rxt-pcre-to-elisp "(\d+)")``, This is not correct. 

Anywhy, we know what we want.

**Comment by r0man** [comment]
@zw963 I'm not using ruby-test-mode myself at the moment. I agree that the existing regular expressions are a bit hard to read, but to be honest I don't mind. Do you plan to add a lot more mappings? Otherwise I would say keep it as it is, and don't pull in another package dependency. @snadorp & @febeling Are you still using this, and have strong opinions about this?

**Comment by snadorp** [comment]
Not using it either currently, so I personally don't mind if we change the format to a clearer one.

**Comment by zw963** [comment]
>> I'm not using ruby-test-mode myself at the moment.

I use ruby-test-mode heavily... (though use ido/helm is help a lot)
I just want wo press one keybinding,  auto switch to the correct test/spec files for me.

>> Do you plan to add a lot more mappings?

Yes, I have write more mapping for make most standard specification is support.
After update, we could still keep all existed(and correct) mapping worked fine.
To be honest,  I always need to add more mapping to ruby-test-mode when I develop
in difference project. and error prone, I have some times recent days, I hope add more
common mapping make this mode more useful.
I will add a new PR for we discuss, any way, we can make it more simple and clear together.

>> Otherwise I would say keep it as it is, and don't pull in another package dependency. 

We could use `pcre2el` generate regexp for us, and replaced in, 
though, I don't think this is a good idea. use `pcre` directly this mode is more good I think.

**Comment by zw963** [comment]
Hi, I add a new PR for this.  #30 
We can review code there.

**Comment by r0man** [comment]
@zw963 Ok, then go for it. Could you please also add some tests for the changes you plan to do?

**Comment by zw963** [comment]
@r0man , OK, you could review the specification I added into first, (for some improper case)
and i will add test for those.

But, before this, i will add a little test for #29, i hope #29 could merged into first.

**Comment by zw963** [comment]
Merged.
