### ISSUE TITLE
Please specify same license in library as in readme

### ISSUE THREAD

**Issue by tarsius** [r0man/ruby-test-mode#42]
The readme says that this is licensed under "GPL either version 3, or (at your option) any later version", while the library header says "This software can be redistributed. GPL v2 applies." Please update the library by adding this text (which is the standard text and therefore allows tools to automatically determine the license):

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this file.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by r0man** [comment]
@febeling are you fine with switching to gpl v3?

**Comment by febeling** [comment]
@r0man yes, fine with me!

**Comment by r0man** [comment]
@tarsius fixed

**Comment by tarsius** [comment]
Thanks!

Please consider using the above standard permission statement. Then I would not have to add an extra match rule to [`elx`](https://github.com/emacscollective/elx), just for this one package.

**Comment by r0man** [comment]
@tarsius Done.

**Comment by tarsius** [comment]
Thanks again!
