### ISSUE TITLE
Correct directory no longer used.

### ISSUE THREAD

**Issue by mijoharas** [r0man/ruby-test-mode#45]
After upgrading to the latest version and running `ruby-test-run` on a file, I get the error message `require cannot load such file -- test_helper (LoadError)`

This implies that the logic for running the test within the rails root is broken. I'll have a look at it when I can.
There was a slightly different bug before, where it would change the directory of the file I was visiting with `setq`.

I think I probably need to dig into exactly how emacs treats `default-directory` to understand this properly.

**Comment by mijoharas** [comment]
@aaronjensen Any ideas on this? Reading your code it looks like it should do what is intended.
Specifically this commit https://github.com/r0man/ruby-test-mode/pull/44/commits/9435a0fa2ed85ad616236a8a30c9052be65998d4

**Comment by mijoharas** [comment]
Hmmm... I think something weird was happening, editing the `.el` file and saving it along with restarting emacs (or something) seems to have stopped this problem from occuring. I'm gonna close this issue. I'll reopen if I get the error coming back.

Sorry about the noise.

**Comment by aaronjensen** [comment]
@mijoharas I think there's an actual bug here having to do with when the file gets byte compiled and the macro gets expanded at that time. I'm going to look into it.

**Comment by mijoharas** [comment]
Ahhh, I didn't really think of that. Nice catch.
